services:
  backend:
    build: ./backend
    environment:
      - PGHOST=database
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  network1:
    name: my-pre-existing-network
    external: true
